name: Release
'on':
  push:
    branches:
      - alpha
jobs:
  release:
    uses: form8ion/.github/.github/workflows/release-package.yml@d7677f1c3126bdc4f0e08f200686b5b00d22d403 # master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
