name: Release
'on':
  push:
    branches:
      - alpha
jobs:
  release:
    uses: form8ion/.github/.github/workflows/release-package.yml@316efe71a8c426187c52f5f0073db9f5d01f79a6 # master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
